<?php

use \Drupal\Core\Entity\EntityInterface;
use \Drupal\node\Entity\Node;
use \Drupal\node\NodeInterface;

/**
 * Implements hook_theme().
 */
function student_hosting_theme() {
  return [
    'student_hosting_formatter' => [
      'variables' => [
        'use_container' => FALSE,
        'use_apply_button' => FALSE,
        'field_name' => NULL,
        'title' => NULL,
        'cost' => 0,
        'currency' => NULL,
        'min_age' => 0,
        'min_years_enrolled' => 0,
        'has_eligibility_requirements' => FALSE,
        'program_parameters' => NULL,
        'expectations' => NULL,
        'has_expectations' => FALSE,
        'school_name' => NULL,
        'school_node_id' => 0,
        'require_jc_record' => FALSE,
        'require_sm_approval' => FALSE,
        'require_recommendation_letter' => FALSE,
        'has_required_documents' => FALSE,
        'jc_record_document_description' => NULL,
        'sm_approval_document_description' => NULL,
        'recommendation_letter_document_description' => NULL
      ],
      'template' => 'student_hosting_formatter',
    ],
  ];
}
