<?php

use \Drupal\Core\Entity\EntityInterface;
use \Drupal\node\Entity\Node;
use \Drupal\node\NodeInterface;

/**
 * Implements hook_theme().
 */
function student_hosting_theme() {
  return [
    'student_hosting_formatter' => [
      'variables' => [
        'title' => NULL,
        'description' => NULL,
        'isWage' => FALSE,
        'fee' => 0,
        'wage' => 0,
        'currency' => NULL,
        'min_age' => 0,
        'min_years_enrolled' => 0,
        'has_eligibility_requirements' => FALSE,
        'program_parameters' => NULL,
        'school_name' => NULL,
        'school_node_id' => NULL,
        'student_hosting_field_name' => NULL
      ],
      'template' => 'student-hosting-formatter',
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 * Executes when a new school entity is inserted.
 * This creates webforms for student hosting applications.
 * The webforms are constructed programatically based on student_hosting fields.
 */
function hook_school_insert(NodeInterface $school) {
  //create_student_guest_application($school);
}

function create_student_guest_application(NodeInterface $school) {
  $current_user = User::load(Drupal::currentUser()->id());
  $application = Node::create([
    'type' => 'application',
    'title' => $school->getTitle() . ' Student Guest Application'
  ]);
  $application->field_school->entity = $school;
  $application->field_applicant->entity = $current_user;
  //$application->webform = create_webform($school->field_student_guest_program->value);
  $application->save();
}

function create_webform(NodeInterface $student_hosting) {
}