<?php

use Drupal\Core\Database\Database;

/**
 * Update database to include expectations column.
 */
function student_hosting_update_8001(&$sandbox) {
    $spec = [
        'type' => 'text'
    ]; 
    $schema = Database::getConnection()->schema();
    $schema->addField('node__field_student_ambassador_program', 'field_student_guest_program_expectations', $spec);
    $schema->addField('node__field_student_ambassador_program', 'field_student_ambassador_program_expectations', $spec);
}

/**
 * Update database to include expectations column (take 2).
 */
function student_hosting_update_8002(&$sandbox) {
    $spec = [
        'type' => 'text'
    ]; 
    $schema = Database::getConnection()->schema();
    $schema->dropField('node__field_student_ambassador_program', 'field_student_guest_program_expectations');
    $schema->addField('node__field_student_guest_program', 'field_student_guest_program_expectations', $spec);
    $schema->addField('node_revision__field_student_guest_program', 'field_student_guest_program_expectations', $spec);
    $schema->addField('node_revision__field_student_ambassador_program', 'field_student_ambassador_program_expectations', $spec);
}

/**
 * Update database to include requirements and questions columns.
 */
function student_hosting_update_8003(&$sandbox) {
    $boolean_spec = [
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => 0
    ];
    $string_spec = [
        'type' => 'text'
    ];
    $schema = Database::getConnection()->schema();
    
    $schema->addField('node__field_student_guest_program', 'field_student_guest_program_require_jc_record', $boolean_spec);
    $schema->addField('node__field_student_guest_program', 'field_student_guest_program_require_sm_approval', $boolean_spec);
    $schema->addField('node__field_student_guest_program', 'field_student_guest_program_require_recommendation_letter', $boolean_spec);
    $schema->addField('node__field_student_guest_program', 'field_student_guest_program_questions', $string_spec);
    
    $schema->addField('node__field_student_ambassador_program', 'field_student_ambassador_program_require_jc_record', $boolean_spec);
    $schema->addField('node__field_student_ambassador_program', 'field_student_ambassador_program_require_sm_approval', $boolean_spec);
    $schema->addField('node__field_student_ambassador_program', 'field_student_ambassador_program_require_recommendation_letter', $boolean_spec);
    $schema->addField('node__field_student_ambassador_program', 'field_student_ambassador_program_questions', $string_spec);
    
    $schema->addField('node_revision__field_student_guest_program', 'field_student_guest_program_require_jc_record', $boolean_spec);
    $schema->addField('node_revision__field_student_guest_program', 'field_student_guest_program_require_sm_approval', $boolean_spec);
    $schema->addField('node_revision__field_student_guest_program', 'field_student_guest_program_require_recommendation_letter', $boolean_spec);
    $schema->addField('node_revision__field_student_guest_program', 'field_student_guest_program_questions', $string_spec);
    
    $schema->addField('node_revision__field_student_ambassador_program', 'field_student_ambassador_program_require_jc_record', $boolean_spec);
    $schema->addField('node_revision__field_student_ambassador_program', 'field_student_ambassador_program_require_sm_approval', $boolean_spec);
    $schema->addField('node_revision__field_student_ambassador_program', 'field_student_ambassador_program_require_recommendation_letter', $boolean_spec);
    $schema->addField('node_revision__field_student_ambassador_program', 'field_student_ambassador_program_questions', $string_spec);
}

/**
 * Update database to drop description column.
 */
function student_hosting_update_8004(&$sandbox) {
    $schema = Database::getConnection()->schema();
    $schema->dropField('node__field_student_guest_program', 'field_student_guest_program_description');
    $schema->dropField('node__field_student_ambassador_program', 'field_student_ambassador_program_description');
    $schema->dropField('node_revision__field_student_guest_program', 'field_student_guest_program_description');
    $schema->dropField('node_revision__field_student_ambassador_program', 'field_student_ambassador_program_description');
}

/**
 * Update database to include "require interview" column
 */
function student_hosting_update_8005(&$sandbox) {
    $boolean_spec = [
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => 0
    ];
    $schema = Database::getConnection()->schema();
    $schema->addField('node__field_student_guest_program', 'field_student_guest_program_require_interview', $boolean_spec);
    $schema->addField('node__field_student_ambassador_program', 'field_student_ambassador_program_require_interview', $boolean_spec);
    $schema->addField('node_revision__field_student_guest_program', 'field_student_guest_program_require_interview', $boolean_spec);
    $schema->addField('node_revision__field_student_ambassador_program', 'field_student_ambassador_program_require_interview', $boolean_spec);
}