# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1-browsers

    working_directory: ~/repo

    steps:
      - checkout
  
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e2:c9:b5:d7:23:2d:0a:78:62:b7:68:8f:5a:87:86:a5"
      - run:
          name: Test connection to host
          command: |
            ssh -v -p 18765 $SSH_HOST
      - run:
          name: Test connection to user
          command: |
            ssh -v -p 18765 $SSH_USER@$SSH_HOST
      - run:
          name: Deploy usin scp
          command: |
            scp -P 18765 -r ..\ $SSH_USER@$SSH_HOST:public_html

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
