<?php

/**
 * @file
 * Module File, consist all related hooks.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_help().
 */
function forum_notification_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.forum_notification':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module can be used to send email to admin or on any specific email id when a content has been posted/updated on Drupal site.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_node_insert().
 */
function forum_notification_node_insert(EntityInterface $node) {
  \Drupal::service('forum_notification.common')->sendMail($node, TRUE);
}

/**
 * Implements hook_mail().
 */
function forum_notification_mail($key, &$message, $params) {
  switch ($key) {
    case 'forum_notification_key':
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
      break;
  }
}
